# Generated by Django 5.2.3 on 2025-07-01 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('photo', models.ImageField(upload_to='chairs/', verbose_name='Фото')),
                ('description', models.CharField(max_length=400, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Стул',
                'verbose_name_plural': 'Стулья',
            },
        ),
    ]
