# Generated by Django 5.2.3 on 2025-07-01 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=200, verbose_name='<UNK>')),
                ('email', models.EmailField(max_length=200, verbose_name='<UNK>')),
                ('phone', models.CharField(max_length=11, verbose_name='<UNK>')),
                ('address', models.CharField(max_length=200, verbose_name='<UNK>')),
            ],
        ),
    ]
